### ISSUE TITLE
crash execute cronolog

### ISSUE THREAD

**Issue by Paul75** [codecapers/cronolog#2]
When execute cronolog : 

Loading cronolog.json from /Users/far-paul/Projects/lucy/sl-outils/prod/sl-server
Task:      cron-refresh
Schedule:  * * * *
Frequency: Every minute
Next:      Today at 4:35 PM
Cronolog log failed.
TypeError: Cannot read property 'replace' of undefined
    at convertMonthName (/usr/local/lib/node_modules/cronolog/node_modules/node-cron/src/convert-expression/month-names-conversion.js:10:31)
    at interprete (/usr/local/lib/node_modules/cronolog/node_modules/node-cron/src/convert-expression/month-names-conversion.js:16:23)
    at interprete (/usr/local/lib/node_modules/cronolog/node_modules/node-cron/src/convert-expression/index.js:38:22)
    at validate (/usr/local/lib/node_modules/cronolog/node_modules/node-cron/src/pattern-validation.js:49:29)
    at new Task (/usr/local/lib/node_modules/cronolog/node_modules/node-cron/src/task.js:38:5)
    at Object.createTask [as schedule] (/usr/local/lib/node_modules/cronolog/node_modules/node-cron/src/node-cron.js:19:16)
    at _loop_1 (/usr/local/lib/node_modules/cronolog/build/index.js:243:18)
    at Cronolog.scheduleTasks (/usr/local/lib/node_modules/cronolog/build/index.js:254:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/cronolog/build/cli.js:19:14)
    at Module._compile (module.js:652:30)

Thanks

**Comment by ashleydavis** [comment]
Please submit example configuration/code so that I can troubleshoot your issue.
